name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['3.0', '3.1.x', '5.0.x' ]
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Install dependencies
      run: dotnet restore ./ClassLibrary2.sln
    - name: Build
      run: dotnet build ./ClassLibrary2.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./ClassLibrary2.sln --no-restore --verbosity normal
    - name: NDepend
      uses: CoderGears/ndepend-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        license: ${{ secrets.NDependLicense }}
        baseline: 91
        customconfig: NDependConfigFile.ndproj
