name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x       
    - name: Install dependencies
      run: dotnet restore ./ClassLibrary2.sln    
    - name: Build
      run: dotnet build ./ClassLibrary2.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test ./ClassLibrary2.sln --no-restore --verbosity normal
    - name: NDepend
      uses: CoderGears/ndepend-action@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
        license: ${{ secrets.NDependLicense }}
        baseline: 91
